version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      NODE_ENV: production
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
